apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs: 
    runtime-config: "api/all=true"
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: 1.28.0
kind: ClusterConfiguration
clusterName: kubernetes
controllerManager: 
  extraArgs: 
    horizontal-pod-autoscaler-use-rest-clients: "true" 
    horizontal-pod-autoscaler-sync-period: "10s" 
    node-monitor-grace-period: "10s"
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
